- amxmodx/scripting/CA_Gag.sma
- amxmodx/scripting/CA_Mute.sma
> fix runtime errors on gag, mute menus (fix #9)

- amxmodx/data/lang/CA_Gag.txt
- amxmodx/scripting/CA_Gag.sma
> Fix menus next back naming

- amxmodx/data/lang/CA_Mute.txt
- amxmodx/scripting/CA_Mute.sma
> enhance mute menu

- amxmodx/data/lang/CA_Mute.txt
- amxmodx/scripting/CA_Mute.sma
> Add new CVar: ca_mute_use_delay

- amxmodx/scripting/CA_Gag.sma
> new cmd: ca_gag_reload_config.

- .github/workflows/build.yml
- amxmodx/scripting/CA_Gag.sma
- amxmodx/scripting/include/CA_GAG_API.inc
> More tests

- amxmodx/scripting/CA_Gag.sma
- amxmodx/scripting/CA_Mute.sma
- amxmodx/scripting/ChatAdditions_Core.sma
- amxmodx/scripting/include/ChatAdditions.inc
close #18
- new func: `CA_Log()` for logging;
- new CVar: `ca_log_type 0 / 1` - for control log dir.
> Add logging system

- amxmodx/configs/ChatAdditions/gag_reasons.cfg
- amxmodx/data/lang/CA_Gag.txt
- amxmodx/scripting/CA_Gag.sma
> Simplify menu

- amxmodx/scripting/CA_Gag.sma
- amxmodx/scripting/CA_Mute.sma
- amxmodx/scripting/ChatAdditions_Core.sma
- amxmodx/scripting/include/ChatAdditions.inc
- amxmodx/scripting/include/ChatAdditions_inc/_MySQL.inc
- amxmodx/scripting/include/ChatAdditions_inc/_SQLite.inc
> Add ca_log_level cvar

- .github/workflows/build.yml
- amxmodx/scripting/CA_Gag.sma
- amxmodx/scripting/CA_Mute.sma
- amxmodx/scripting/ChatAdditions_Core.sma
- amxmodx/scripting/include/CA_GAG_API.inc
- amxmodx/scripting/include/ChatAdditions.inc
- amxmodx/scripting/include/ChatAdditions_inc/_GameCMS.inc
- amxmodx/scripting/include/ChatAdditions_inc/_MySQL.inc
- amxmodx/scripting/include/ChatAdditions_inc/_SQLite.inc
- amxmodx/scripting/include/gamecms/gamecms_addadmin.inl
- amxmodx/scripting/include/gamecms/gamecms_admin_remove.inl
- amxmodx/scripting/include/gamecms/gamecms_natives.inl
- amxmodx/scripting/include/gamecms/gamecms_stocks.inl
- amxmodx/scripting/include/gamecms/gamecms_user_settings.inl
- amxmodx/scripting/include/gamecms/gamecms_users_groups.inl
- amxmodx/scripting/include/gamecms5.inc
> Game cms support

- amxmodx/scripting/include/ChatAdditions_inc/_GameCMS.inc
- amxmodx/scripting/include/ChatAdditions_inc/_MySQL.inc
- amxmodx/scripting/include/ChatAdditions_inc/_SQLite.inc
> more saferty string into SQL queries 

- amxmodx/scripting/include/ChatAdditions_inc/_MySQL.inc
- amxmodx/scripting/include/ChatAdditions_inc/_SQLite.inc
> Fix gag on FOREVER time

- .github/build_changelog_config.json
- .github/workflows/release.yml
> Add auto-build release changelog

- .github/workflows/upload_release_asset.yml
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/CA_Mute.sma
- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
> update version by CI on plugins

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/CA_Mute.sma
- cstrike/addons/amxmodx/scripting/CA_Storage_SQLite.sma
- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
> Rework log system. Add new native CA_Log()

- cstrike/addons/amxmodx/configs/plugins/CA_Gag.cfg
- cstrike/addons/amxmodx/configs/plugins/ca_gag_reasons.cfg
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
> Add human-friendly time parsing from configs

- cstrike/addons/amxmodx/configs/plugins/CA_Gag.cfg
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> Add new CVar ca_gag_remove_only_own_gag

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> Load full gag data on client connected

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> FIX: Save expireAt time on gag edit

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> FIX: Negative time rejected on enter gag time

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> Allow enter reason & time only for `ca_gag_access_flags_high` admins

- cstrike/addons/amxmodx/configs/plugins/CA_Gag.cfg
- cstrike/addons/amxmodx/data/lang/CA_Gag.txt
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> Skip extra menus when reason or time or flags already set

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> Can't edit reason and time on Edit gag menu

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/include/CA_GAG_API.inc
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
> Add new command: `amx_gag` 

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> Add support arguments for `say /gag` <nickname> command

- cstrike/addons/amxmodx/configs/plugins/CA_Gag.cfg
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
Close https://github.com/ChatAdditions/ChatAdditions_AMXX/issues/80
> Add sound UX

- cstrike/addons/amxmodx/data/lang/CA_Gag.txt
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> Added notifications to gagged players

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> 🐛 Reset gag data on player disconnect

- cstrike/addons/amxmodx/scripting/CA_Storage_SQLite.sma
> Add autoload SQL modules

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> FIX: Buffer error on amx_gag command

- cstrike/addons/amxmodx/configs/plugins-ChatAdditions.ini
- cstrike/addons/amxmodx/scripting/CA_Mute.sma
- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
> Add support in-game Mute manager

- cstrike/addons/amxmodx/configs/plugins-ChatAdditions.ini
- cstrike/addons/amxmodx/configs/plugins/ChatAdditions.cfg
- cstrike/addons/amxmodx/scripting/CA_Storage_CSBans.sma
- cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
- cstrike/addons/amxmodx/scripting/CA_Storage_SQLite.sma
- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
> Add CVar for choose storage type `ca_storage_type`

- cstrike/addons/amxmodx/data/lang/CA_Mute.txt
- cstrike/addons/amxmodx/scripting/CA_Mute.sma
> Not show `/mute` menu when haven't players

- cstrike/addons/amxmodx/data/lang/CA_Gag.txt
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> Add gag flags for reasons list

- cstrike/addons/amxmodx/data/lang/CA_Gag.txt
- cstrike/addons/amxmodx/data/lang/CA_Mute.txt
> Add Spanish translation for plugins

- cstrike/addons/amxmodx/scripting/CA_Storage_CSBans.sma
- cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
- cstrike/addons/amxmodx/scripting/CA_Storage_SQLite.sma
> FIX: Error with uninitialized SQL handler

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
> Add new CVar: ca_gag_block_nicnkame_change

- .github/workflows/build.yml
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
- publish.sh
> Add artifacts for CI builds

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> FIX: Error when hasn't reasons template

- cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
> FIX: Wrong gag type by convert

- cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
> FIX: Dead players can't talk to anyone

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> added check for 'amx_gag' command, if player already has gag

- cstrike/addons/amxmodx/data/lang/CA_Addon_DeathMute.txt
- cstrike/addons/amxmodx/data/lang/CA_Gag.txt
- cstrike/addons/amxmodx/data/lang/CA_Mute.txt
> Add Lang: [de]

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/include/CA_GAG_API.inc
> Implement CA_Gag API

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/CA_Mute.sma
- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
> Disabling cmdaccess support for registered plugin commands

- cstrike/addons/amxmodx/configs/plugins/CA_Addon_DeathMute.cfg
- cstrike/addons/amxmodx/configs/plugins/CA_Gag.cfg
- cstrike/addons/amxmodx/configs/plugins/CA_Mute.cfg
- cstrike/addons/amxmodx/data/lang/CA_Addon_DeathMute.txt
- cstrike/addons/amxmodx/data/lang/CA_Gag.txt
- cstrike/addons/amxmodx/data/lang/CA_Mute.txt
- cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/CA_Mute.sma
Close https://github.com/ChatAdditions/ChatAdditions_AMXX/issues/158
> Add support colors for prefixes

- cstrike/addons/amxmodx/scripting/CA_Mute.sma
- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
> New file-logs names; Folder for each CA plugin

- cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
> fix 213 warn

- cstrike/addons/amxmodx/data/lang/CA_Addon_DeathMute.txt
- cstrike/addons/amxmodx/data/lang/CA_Gag.txt
- cstrike/addons/amxmodx/data/lang/CA_Mute.txt
> fixed color of chat tag

- cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Addon_DeathMute.cfg
- cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
> Add new CVar `ca_deathmute_immunity_flags`

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> CA_Gag: Add block for `amx_tsay`, `amx_csay`

- cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
> Small code refactoring & Bug with DeathMute hud fixed

- cstrike/addons/amxmodx/scripting/CA_Storage_CSBans.sma
- cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
Fix https://github.com/ChatAdditions/ChatAdditions_AMXX/issues/191
> FIX: `CA_Storage`: Add more safety for slow DB.

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- The bracket opens now even if the pattern does not have a set time
- Flags are now yellow, even if the pattern does not have a set time
- The closing bracket is no longer shown if there is no opening bracket (thx @emtrAAAA (telegram) for report)
> Cosmetic fixes in the gag reasons menu

- .github/workflows/CI.yml
> CI: update AMXModX compiler version to `1.10`

- cstrike/addons/amxmodx/data/lang/CA_Gag.txt
- cstrike/addons/amxmodx/data/lang/CA_Mute.txt
> Fix spelling errors in `RU` lang

- .github/workflows/remove-old-artifacts.yml
> Add `GitHub Action` for Remove old artifacts

- cstrike/addons/amxmodx/scripting/CA_Storage_CSBans.sma
- cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
- cstrike/addons/amxmodx/scripting/CA_Storage_PGBans.sma
> FIX: buggy default `OnConfigsExecuted()` from amxx

- cstrike/addons/amxmodx/configs/plugins/ChatAdditions/ChatAdditions_core.cfg
- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
- cstrike/addons/amxmodx/scripting/include/grip.inc
> Notification of new version availability

- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
Forwards `CA_Client_Say` and `CA_Client_SayTeam` can now transmit the message string
> Core API enhance

- cstrike/addons/amxmodx/data/lang/CA_AntiFlood.txt
- cstrike/addons/amxmodx/scripting/CA_AntiFlood.sma
update codestyle like in a whole project
> Update codestyle for AntiFlood

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> `EditGag` menu fixes

- cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
fix https://github.com/ChatAdditions/ChatAdditions_AMXX/issues/227
> Fix admin link in `GameCMS` comms page

- cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Gag.cfg
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> Add CVar `ca_gag_own_reason_enabled` in CA GAG

- cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
> GameCMS storage: fix get admin id error

- cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
close https://github.com/ChatAdditions/ChatAdditions_AMXX/issues/274#issue-1231351898
> GameCMS Storage: Getting the server address from CVar

- cstrike/addons/amxmodx/data/lang/CA_Gag.txt
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
fix https://github.com/ChatAdditions/ChatAdditions_AMXX/issues/267
> CA:Gag: fix wrong exit item name

- cstrike/addons/amxmodx/scripting/CA_Addon_RankRestrictions.sma
- cstrike/addons/amxmodx/scripting/CA_Addon_RequestUnGag.sma
- cstrike/addons/amxmodx/scripting/CA_AntiFlood.sma
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
> Update `CA_Client_Say()` with new param: `bool: isTeamMessage`

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> gag: fixed the team chat gag that doesn't work

- cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
- FIX: Players can hear dead admin
- FIX: alive admin can't hear dead players
> Fix: deathmute admin immunity

- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
> ChatAdditions.inc: get seconds const from time.inc

- cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
Related to https://github.com/ChatAdditions/ChatAdditions_AMXX/commit/df22f3a1080776554cef8acdfd6307b5ee26062e
Fix #276 again
> ChatAdditions.inc: Fix compilation on AMXX 1.9.0

- cstrike/addons/amxmodx/scripting/CA_Mute.sma
> CA_Mute: Delete menu time

- cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
> DeathMute: fix compile warn

- cstrike/addons/amxmodx/scripting/CA_Gag.sma
> CA_Gag: Changed the way to read the config

- cstrike/addons/amxmodx/scripting/CA_Addon_RequestUnGag.sma
- cstrike/addons/amxmodx/scripting/CA_AntiFlood.sma
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/CA_Mute.sma
- Destroy menus once in handler
- Codestyle updates
> Optimization and codestyle

- cstrike/addons/amxmodx/configs/plugins/ChatAdditions/ca_gag_chat_whitelist_cmds.cfg
- cstrike/addons/amxmodx/scripting/CA_Gag.sma
- cstrike/addons/amxmodx/scripting/include/CA_GAG_API.inc
chat commands will be allowed even if the player is gagged
> Gag: Implemented whitelist for chat commands

- cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Addon_RankRestrictions.cfg
- cstrike/addons/amxmodx/scripting/CA_Addon_RankRestrictions.sma
> Rank restrictions: Different CVars for restrict text & voice chats

- cstrike/addons/amxmodx/scripting/CA_Mute.sma
resolve https://github.com/ChatAdditions/ChatAdditions_AMXX/issues/198
> Add SQLite storage for `/mute`
